{
 "title": "Application performance",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Application performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage per app",
   "type": "stat",
   "description": "Actual physical RAM used by the Node.js process",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=~\"backend-service|frontend-service\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Application CPU Usage (%)",
   "type": "gauge",
   "description": " the average CPU usage percentage of the frontend and backend services over time",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=~\"frontend-service|backend-service\"}[1m]) * 100\r\n",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Uptime of application",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{app=~\"backend-service|frontend-service\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Application status",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "app_health{app=~\"backend-service|frontend-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Frontend metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "User interaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "frontend_user_interactions{app=\"frontend-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Page views",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "frontend_page_views{app=\"frontend-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}